- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create workstation inventory
    add_host:
      name: workstation-{{osp_GUID}}.rhpds.opentlc.com
      group: workstation

- hosts: workstation
  become: yes
  roles:
    - osp-servers
